---
name: Update Evervault Relay

on:
  push:
    branches:
      - main

jobs:
  - name: Install Evervault CLI
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sh <(curl https://cli.evervault.com/v4/install -sL)

  - name: Update Evervault Relays 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: export EV_API_KEY=${{ secrets.EV_API_KEY }} EV_APP_UUID=${{ secrets.EV_APP_UUID }} ev relay deploy
---
