name: Update Evervault Relay

on:
  push:
    branches:
      - main

jobs:
  update-relay:
    name: Update Relay
    runs-on: ubuntu-latest
    steps:
      - name: Install Evervault CLI
        run: sh <(curl https://cli.evervault.com/v4/install -sL)

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update
        run: EV_API_KEY=${{ secrets.EV_API_KEY }} EV_APP_UUID=${{ secrets.EV_APP_UUID }} ev relay deploy
